### ISSUE TITLE
SUNRISE: new indicators

### ISSUE THREAD

**Issue by christinenam** [ludwiglierhammer/index_calculator#17]
heatwave_frequency
heatwave_max_length
heatwave_total_length

dry_spell_frequency
dry_spell_max_length
dry_spell_total_length

prep for SPEI

(ERA + CORDEX)

**Comment by ludwiglierhammer** [comment]
Regaring `SPEI` there are some things that have to be fixed/reworked in xclim:
 https://github.com/Ouranosinc/xclim/pull/1311

**Comment by ludwiglierhammer** [comment]
The following indices are now implemented in `index_calculator`:

heatwave_frequency: `HWf`
heatwave_max_length: `HWx`
heatwave_total_length: `HWn`
dry_spell_frequency: `DSf`
dry_spell_max_length: `DSx`
dry_spell_total_length: `DSn`

Waiting for new release **v0.8.0**.
