### ISSUE TITLE
new version 0.11.0

### ISSUE THREAD

**Issue by ludwiglierhammer** [ludwiglierhammer/index_calculator#37]
Moin @larsbuntemeyer,

sollen wir eine neue Version (v0.11.0) releasen und auf pypi veröffentlichen?

VG, Ludwig

**Comment by larsbuntemeyer** [comment]
Ja, ich schau mal, ob ich das machen kann und das mit den rechten funktioniert...

**Comment by ludwiglierhammer** [comment]
ich hab dich bei pypi mal als owner eingetragen.
Damit solltest du eigentlich die erforderlichen Rechte haben.

**Comment by larsbuntemeyer** [comment]
bei gelegenheit könntest du mich noch bei `readthedocs` --> Administration --> Entwickler --> Betreuer hinzufügen (larsbuntemeyer)...  THANKS!

**Comment by ludwiglierhammer** [comment]
hab dich hinzugefügt. hat das geklappt?

**Comment by ludwiglierhammer** [comment]
Kannst du auch ein neues Release erstellen und eine neue Version auf pypi veröffentlichen oder kann das nur ich?

**Comment by ludwiglierhammer** [comment]
dann könnten wir auch mal die Authorenliste updaten `AUTHORS.rst`

**Comment by ludwiglierhammer** [comment]
wie wird eigentlich die Authorenliste bei zenodo festgelegt?
