### ISSUE TITLE
drs

### ISSUE THREAD

**Issue by KatharinaBuelow** [ludwiglierhammer/index_calculator#42]
Hi, 
jetzt werden die Ergebnisse nicht mehr in
xcalc_0-10-1
sondern in
xcalc_0-10-1-dev49+g4ff4923
geschrieben

**Comment by KatharinaBuelow** [comment]
es lag an meinem environment

**Comment by larsbuntemeyer** [comment]
Das build system brauchte ein update (e.g., die versions nummer wird nun automatisch aus dem tag generiert), siehe auch

* https://github.com/ludwiglierhammer/index_calculator/pull/40
* https://github.com/pypa/setuptools_scm
